server:
  port: 8080
  error:
    whitelabel:
      enabled: false
com:
  wanted:
    cqrs:
      jwt:
        # test 24시간 60 * 60 * 1000
        access-expire-milli: 86400000
        # test 3일 3 * 24 * 60 * 60 * 1000
        refresh-expire-milli: 259200000
        secret-key: "testSecreteKeyW3e4r5tt67yy126sdhds7i128hd7q621"

# logback-spring config 함께 확인
logging:
  # 자동 설정 사용
  # config: classpath:logback-spring-dev.xml
  level:
    com.wanted.cqrs: debug
    org.springframework.web.client: trace
  file:
    name: ./logs/application-logging.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

spring:
  application:
    name: cqrs
  profiles:
    default: dev
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: 'cqrs_dev'
    password: '!q2w3e4r'
    hikari:
      pool-name: Hikari
      maximum-pool-size: 4
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      #      ddl-auto: create
      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#    jdbc-type-for-null: varchar
#  mapper-locations: classpath:/database/mappers/**/*Mapper.xml
#  type-aliases-package: com.wanted.cqrs.apis
