log.file.path=./logs
log.file.name=application-logging.log
log.console.pattern=[%thread] %highlight(%-5level) %cyan(%logger{15})[%line] - %msg%n
log.logging.pattern=[%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%thread] %-5level %logger{35}[%line] - %msg%n